---
- name: Configure Flask App Server
  hosts: flask_app
  become: yes

  vars:
    app_dir: /home/ubuntu/flaskapp

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install essential system packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - git
        state: present

    - name: Install system dependencies for mysqlclient
      apt:
        name:
          - build-essential
          - pkg-config
          - libmysqlclient-dev
          - python3-dev
        state: present

    - name: Clone Flask App Repository
      git:
        repo: https://github.com/manuelherreram/todo-flask-devops.git
        dest: "{{ app_dir }}"
        version: main

    - name: Set up Python virtual environment
      command: python3 -m venv venv
      args:
        chdir: "{{ app_dir }}"

    - name: Install Python dependencies from requirements.txt
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"

    - name: Copy .env file from template
      template:
        src: "../roles/flask/templates/.env.j2"
        dest: "{{ app_dir }}/.env"
        owner: ubuntu
        mode: "0600"

    - name: Create systemd service for Gunicorn
      copy:
        dest: /etc/systemd/system/flaskapp.service
        content: |
          [Unit]
          Description=Gunicorn service for Flask To-Do App
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory={{ app_dir }}
          EnvironmentFile={{ app_dir }}/.env
          ExecStart={{ app_dir }}/venv/bin/gunicorn -b 0.0.0.0:5000 run:app
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Start flaskapp

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start flaskapp
      systemd:
        name: flaskapp
        enabled: yes
        state: started
